USE [esencialDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[codigosPostales](
	[codigoPostalId] [bigint] IDENTITY(1,1) NOT NULL,
	[ciudadId] [nchar](10) NOT NULL,
	[codigoPostal] [int] NOT NULL,
	[distrito] [varchar](50) NOT NULL,
 CONSTRAINT [PK_codigosPostales] PRIMARY KEY CLUSTERED 
(
	[codigoPostalId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO