USE [master]
GO

/****** Object:  Database [esencialDB]    Script Date: 29/4/2023 19:36:02 ******/
DROP DATABASE [esencialDB]
GO

/****** Object:  Database [esencialDB]    Script Date: 29/4/2023 19:36:03 ******/
CREATE DATABASE [esencialDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'esencialDB', FILENAME = N'D:\Programas\MSSQL16.MSSQLSERVER\MSSQL\DATA\esencialDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'esencialDB_log', FILENAME = N'D:\Programas\MSSQL16.MSSQLSERVER\MSSQL\DATA\esencialDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [esencialDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [esencialDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [esencialDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [esencialDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [esencialDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [esencialDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [esencialDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [esencialDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [esencialDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [esencialDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [esencialDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [esencialDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [esencialDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [esencialDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [esencialDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [esencialDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [esencialDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [esencialDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [esencialDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [esencialDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [esencialDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [esencialDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [esencialDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [esencialDB] SET RECOVERY FULL 
GO

ALTER DATABASE [esencialDB] SET  MULTI_USER 
GO

ALTER DATABASE [esencialDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [esencialDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [esencialDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [esencialDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [esencialDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [esencialDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [esencialDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [esencialDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [esencialDB] SET  READ_WRITE 
GO

