SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[gobiernos](
	[gobiernoId] [int] IDENTITY(1,1) NOT NULL,
	[regionId] [int] NOT NULL,
	[cuentaBanco] [varchar](30) NOT NULL,
 CONSTRAINT [PK_gobiernos] PRIMARY KEY CLUSTERED 
(
	[gobiernoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO