SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[inspectores](
	[inspectorId] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NOT NULL,
	[profilePic] [varchar](100) NOT NULL,
	[deleted] [bit] NOT NULL,
	[apellido] [varchar](50) NOT NULL,
 CONSTRAINT [PK_inspectores] PRIMARY KEY CLUSTERED 
(
	[inspectorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO