SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[subproductores](
	[subproductorId] [bigint] IDENTITY(1,1) NOT NULL,
	[productorId] [int] NOT NULL,
	[deleted] [bit] NOT NULL,
	[direccionId] [bigint] NOT NULL,
 CONSTRAINT [PK_productorXlocalidades] PRIMARY KEY CLUSTERED
(
	[subproductorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO